[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "https://aspect.netlify.app"
  to = "https://tinytools.design/ratio"
  status = 301

[[redirects]]
  from = "https://aspect.netlify.com"
  to = "https://tinytools.design/ratio"
  status = 301
